In [1]:
from numpy import array
from keras.preprocessing.text import one_hot
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers.embeddings import Embedding

In [2]:
corpus = [
    # Positive Reviews

    'This is an excellent movie',
    'The move was fantastic I like it',
    'You should watch it is brilliant',
    'Exceptionally good',
    'Wonderfully directed and executed I like it',
    'Its a fantastic series',
    'Never watched such a brillent movie',
    'It is a Wonderful movie',

    # Negtive Reviews

    "horrible acting",
    'waste of money',
    'pathetic picture',
    'It was very boring',
    'I did not like the movie',
    'The movie was horrible',
    'I will not recommend',
    'The acting is pathetic'
]

sentiments = array([1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0])

In [3]:
from nltk.tokenize import word_tokenize

all_words = []
for sent in corpus:
    tokenize_word = word_tokenize(sent)
    for word in tokenize_word:
        all_words.append(word)
        
unique_words = set(all_words)
print(len(unique_words))

embedded_sentences = [one_hot(sent, 50) for sent in corpus]
print(embedded_sentences)

45
[[30, 24, 3, 2, 26], [11, 7, 40, 24, 5, 10, 22], [13, 45, 17, 22, 24, 18], [48, 5], [35, 26, 7, 29, 5, 10, 22], [42, 43, 24, 25], [48, 31, 4, 43, 39, 26], [22, 24, 43, 17, 26], [17, 15], [6, 6, 15], [49, 37], [22, 40, 48, 9], [5, 22, 44, 10, 11, 26], [11, 26, 40, 17], [5, 42, 44, 9], [11, 15, 24, 49]]


In [4]:
word_count = lambda sentence: len(word_tokenize(sentence))
longest_sentence = max(corpus, key=word_count)
length_long_sentence = len(word_tokenize(longest_sentence))

In [5]:
padded_sentences = pad_sequences(embedded_sentences, length_long_sentence, padding='post')
print(padded_sentences)

[[30 24  3  2 26  0  0]
 [11  7 40 24  5 10 22]
 [13 45 17 22 24 18  0]
 [48  5  0  0  0  0  0]
 [35 26  7 29  5 10 22]
 [42 43 24 25  0  0  0]
 [48 31  4 43 39 26  0]
 [22 24 43 17 26  0  0]
 [17 15  0  0  0  0  0]
 [ 6  6 15  0  0  0  0]
 [49 37  0  0  0  0  0]
 [22 40 48  9  0  0  0]
 [ 5 22 44 10 11 26  0]
 [11 26 40 17  0  0  0]
 [ 5 42 44  9  0  0  0]
 [11 15 24 49  0  0  0]]


In [8]:
model = Sequential()
model.add(Embedding(50, 20, input_length=length_long_sentence))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])
print(model.summary())

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 7, 20)             1000      
_________________________________________________________________
flatten (Flatten)            (None, 140)               0         
_________________________________________________________________
dense (Dense)                (None, 1)                 141       
Total params: 1,141
Trainable params: 1,141
Non-trainable params: 0
_________________________________________________________________
None


In [9]:
model.fit(padded_sentences, sentiments, epochs=100, verbose=1)
loss, accuracy = model.evaluate(padded_sentences, sentiments, verbose=0)
print('Accuracy: %f' % (accuracy*100))

Epoch 1/100
1/1 [==============================] - 0s 36ms/step - loss: 0.6977 - acc: 0.3750
Epoch 2/100
1/1 [==============================] - 0s 3ms/step - loss: 0.6941 - acc: 0.4375
Epoch 3/100
1/1 [==============================] - 0s 2ms/step - loss: 0.6905 - acc: 0.5000
Epoch 4/100
1/1 [==============================] - 0s 4ms/step - loss: 0.6869 - acc: 0.5625
Epoch 5/100
1/1 [==============================] - 0s 4ms/step - loss: 0.6833 - acc: 0.6250
Epoch 6/100
1/1 [==============================] - 0s 3ms/step - loss: 0.6798 - acc: 0.6875
Epoch 7/100
1/1 [==============================] - 0s 3ms/step - loss: 0.6763 - acc: 0.8750
Epoch 8/100
1/1 [==============================] - 0s 2ms/step - loss: 0.6727 - acc: 1.0000
Epoch 9/100
1/1 [==============================] - 0s 3ms/step - loss: 0.6692 - acc: 1.0000
Epoch 10/100
1/1 [==============================] - 0s 3ms/step - loss: 0.6657 - acc: 1.0000
Epoch 11/100
1/1 [==============================] - 0s 3ms/step - loss: 0.6622

1/1 [==============================] - 0s 3ms/step - loss: 0.3245 - acc: 1.0000
Epoch 89/100
1/1 [==============================] - 0s 3ms/step - loss: 0.3201 - acc: 1.0000
Epoch 90/100
1/1 [==============================] - 0s 2ms/step - loss: 0.3158 - acc: 1.0000
Epoch 91/100
1/1 [==============================] - 0s 3ms/step - loss: 0.3115 - acc: 1.0000
Epoch 92/100
1/1 [==============================] - 0s 2ms/step - loss: 0.3073 - acc: 1.0000
Epoch 93/100
1/1 [==============================] - 0s 2ms/step - loss: 0.3031 - acc: 1.0000
Epoch 94/100
1/1 [==============================] - 0s 3ms/step - loss: 0.2989 - acc: 1.0000
Epoch 95/100
1/1 [==============================] - 0s 3ms/step - loss: 0.2948 - acc: 1.0000
Epoch 96/100
1/1 [==============================] - 0s 3ms/step - loss: 0.2907 - acc: 1.0000
Epoch 97/100
1/1 [==============================] - 0s 2ms/step - loss: 0.2866 - acc: 1.0000
Epoch 98/100
1/1 [==============================] - 0s 3ms/step - loss: 0.2827 - ac

In [10]:
from keras.preprocessing.text import Tokenizer
word_tokenizer = Tokenizer()
word_tokenizer.fit_on_texts(corpus)
vocab_length = len(word_tokenizer.word_index) + 1

embedded_sentences = word_tokenizer.texts_to_sequences(corpus)
print(embedded_sentences)

[[14, 3, 15, 16, 1], [4, 17, 6, 9, 5, 7, 2], [18, 19, 20, 2, 3, 21], [22, 23], [24, 25, 26, 27, 5, 7, 2], [28, 8, 9, 29], [30, 31, 32, 8, 33, 1], [2, 3, 8, 34, 1], [10, 11], [35, 36, 37], [12, 38], [2, 6, 39, 40], [5, 41, 13, 7, 4, 1], [4, 1, 6, 10], [5, 42, 13, 43], [4, 11, 3, 12]]
